CC          = gcc
LIBS        = ../../tk-8.0/unix/libtk8.0.a ../../tcl-8.0/unix/libtcl8.0.a ../../common/libuclmmbase.a -lX11 -lm
CFLAGS      = -g -O -I../../tk-8.0/generic -I../../tcl-8.0/generic -I../../common $(INCLUDES) -DSYSV -DSGI -DCANT_MCAST_BIND -DNORANDPROTO -DAUTH

all:sdr

install:
# this has been changed to the install dir of sdr
	rm -f /usr/local/bin/sdr
	cp ./sdr /usr/local/bin/sdr
	chmod 755 /usr/local/bin/sdr

