CC          = gcc -g -O
INCLUDES    = -I/cs/research/mice/starship/common/freebsd/include -I/usr/X11R6/include
LIB_DIR     = /cs/research/mice/starship/common/freebsd/lib
LIBS        = $(LIB_DIR)/libtk80.a $(LIB_DIR)/libtcl80.a -lm -L/usr/X11R6/lib -lX11
LIBRARY_TCL = $(LIB_DIR)/tcl8.0
LIBRARY_TK  = $(LIB_DIR)/tk8.0
CFLAGS      = $(INCLUDES) -DDIFF_BYTE_ORDER -DFREEBSD -DNORANDPROTO -DDEFINED_ERRLIST -Wall -DAUTH

all::	sdr sip_server
install:
	cp ./sdr /cs/research/mice/speedy/common/freebsd/bin/sdr
	chmod 755 /cs/research/mice/speedy/common/freebsd/bin/sdr
