CC=gcc
INCLUDES=-I/usr/local/include -I/usr/X11R6/include
LIB_DIR=/usr/local/lib
LIBS= $(LIB_DIR)/libtk41.a $(LIB_DIR)/libtcl75.a -lm -L/usr/X11R6/lib -lX11
CFLAGS=-ggdb $(INCLUDES) -DFREEBSD -Wall -DNORANDPROTO -DDEFINED_ERRLIST
LIBRARY_TCL = $(LIB_DIR)/tcl7.5
LIBRARY_TK = $(LIB_DIR)/tk4.1
all::	sdr
install:
	cp ./sdr /cs/research/mice/speedy/common/freebsd/bin/sdr
	chmod 755 /cs/research/mice/speedy/common/freebsd/bin/sdr
