CC          = gcc -g -O
INCLUDES    = -I/usr/X11R6/include -I../../tk-8.0/generic -I../../tcl-8.0/generic -I../../common
LIBS        = ../../tk-8.0/unix/libtk80.a ../../tcl-8.0/unix/libtcl80.a ../../common/libuclmmbase.a -lm -L/usr/X11R6/lib -lX11 -lz
CFLAGS      = $(INCLUDES) -DDIFF_BYTE_ORDER -DFREEBSD -DNORANDPROTO -DDEFINED_ERRLIST -Wall -DAUTH -DHAVE_ZLIB -DFreeBSD -DHAVE_CONFIG_H

all::	sdr 
install:
	cp ./sdr /cs/research/mice/speedy/common/freebsd/bin/sdr
	chmod 755 /cs/research/mice/speedy/common/freebsd/bin/sdr
