CC          = gcc -g -O
INCLUDES    = -I../../tk-8.0/generic -I../../tcl-8.0/generic -I../../common/src
LIBS        = ../../tk-8.0/unix/libtk8.0.a ../../tcl-8.0/unix/libtcl8.0.a ../../common/src/libuclmmbase.a -L/usr/X11R6/lib -lX11 -lc -lm -ldl -lresolv
CFLAGS = $(INCLUDES) -Wall -DNORANDPROTO -DDIFF_BYTE_ORDER -DAUTH -DLinux $(IFLAGS)

all::	sdr


